# Generated by Django 4.1.7 on 2023-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='film1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
